import { Injectable } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { MercadoPagoConfig } from './mercadopago.config';
import { MercadoPagoUnavailableError } from './mercadopago.client';

const TERMINAL_ACTIONS_URL = 'https://api.mercadopago.com/terminals/v1/actions';
const MAX_IMAGE_BYTES = 1_000_000;

export interface PrintReceiptImageInput {
  terminalId: string;
  /** Internal id only — must never carry PII (dni, name, email). */
  externalReference: string;
  /**
   * One per logical print attempt. Generated by the caller (not here) so it
   * can be persisted alongside the attempt's outcome even when this call
   * itself fails.
   */
  idempotencyKey: string;
  /** PNG or JPEG bytes, at most 1MB. */
  imageBuffer: Buffer;
}

export interface PrintReceiptImageResult {
  idempotencyKey: string;
  /**
   * Mercado Pago's own id for the created action — required to look up or
   * cancel it later via getAction/cancelAction. A terminal only holds one
   * queued action at a time; without this id a stuck one can't be found
   * again (see the 2026-09-02 incident: a successful create whose action
   * was never consumed by the terminal blocked every later print with
   * `already_queued_order_on_terminal`, and it had to be diagnosed by hand
   * because this id wasn't kept anywhere).
   */
  actionId?: string;
  status?: string;
  responseBody: unknown;
}

export interface TerminalAction {
  id: string;
  status?: string;
  statusDetail?: string;
}

interface RawActionResponse {
  id?: string;
  status?: string;
  status_detail?: string;
}

/**
 * Talks to Mercado Pago's Point "impressions" endpoint (terminal actions,
 * `type: "print"`) — a raw REST surface outside the `mercadopago` npm SDK,
 * so it gets its own client rather than living on MercadoPagoClient. Never
 * creates a payment; the terminal just prints whatever image it's given.
 */
@Injectable()
export class MercadoPagoTerminalPrinterClient {
  constructor(private readonly config: MercadoPagoConfig) {}

  private requireAccessToken(): string {
    if (!this.config.enabled || !this.config.accessToken) {
      throw new MercadoPagoUnavailableError(
        'Mercado Pago is disabled (MP_ENABLED is not "true"); no client is available.',
      );
    }
    return this.config.accessToken;
  }

  private async request(
    operation: string,
    url: string,
    init: RequestInit,
  ): Promise<unknown> {
    let response: Response;
    try {
      response = await fetch(url, init);
    } catch (err) {
      const detail = err instanceof Error ? err.message : String(err);
      throw new MercadoPagoUnavailableError(
        `Mercado Pago terminal ${operation} request failed: ${detail}`,
      );
    }

    if (!response.ok) {
      const text = await response.text().catch(() => '');
      throw new MercadoPagoUnavailableError(
        `Mercado Pago terminal ${operation} failed (status=${response.status}): ${text}`,
      );
    }

    return response.status === 204 ? undefined : response.json();
  }

  async printReceiptImage(
    input: PrintReceiptImageInput,
  ): Promise<PrintReceiptImageResult> {
    const accessToken = this.requireAccessToken();
    if (input.imageBuffer.length > MAX_IMAGE_BYTES) {
      throw new Error(
        `Receipt image is too large to print (${input.imageBuffer.length} bytes, max 1MB).`,
      );
    }

    const { idempotencyKey } = input;
    const responseBody = (await this.request('print', TERMINAL_ACTIONS_URL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
        'X-Idempotency-Key': idempotencyKey,
      },
      body: JSON.stringify({
        type: 'print',
        config: {
          point: {
            terminal_id: input.terminalId,
            subtype: 'image',
          },
        },
        external_reference: input.externalReference,
        content: input.imageBuffer.toString('base64'),
      }),
    })) as RawActionResponse;

    return {
      idempotencyKey,
      actionId: responseBody.id,
      status: responseBody.status,
      responseBody,
    };
  }

  /** Real-time status of a previously created action — 'created' | 'on_terminal' | ... */
  async getAction(actionId: string): Promise<TerminalAction> {
    const accessToken = this.requireAccessToken();
    const body = (await this.request(
      'get-action',
      `${TERMINAL_ACTIONS_URL}/${actionId}`,
      {
        method: 'GET',
        headers: { Authorization: `Bearer ${accessToken}` },
      },
    )) as RawActionResponse;

    return {
      id: body.id ?? actionId,
      status: body.status,
      statusDetail: body.status_detail,
    };
  }

  /**
   * Cancels an action while it is still `created` — Mercado Pago refuses
   * this once the terminal has already picked it up. Deliberately never
   * called automatically from the print flow: a terminal's "already queued"
   * conflict can just as easily be a live card payment in progress, and
   * auto-cancelling that would cancel a real sale. This is for a human
   * (or an admin tool) to call after confirming, via getAction, that the
   * thing occupying the queue really is our own stuck action.
   */
  async cancelAction(actionId: string): Promise<void> {
    const accessToken = this.requireAccessToken();
    await this.request(
      'cancel-action',
      `${TERMINAL_ACTIONS_URL}/${actionId}/cancel`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
          'X-Idempotency-Key': randomUUID(),
        },
      },
    );
  }
}
