import { useState } from "react";
import { Dumbbell, Menu, X } from "lucide-react";
import Container from "../common/Container";
import Button from "../common/Button";

const navLinks = [
  { label: "Inicio", href: "/" },
  { label: "Clases", href: "/class" },
  { label: "Entrenadores", href: "/trainers" },
  { label: "Planes", href: "/membership" },
  { label: "Reseñas", href: "/reviews" },
  { label: "Sobre nosotros", href: "/about" },
  { label: "Contacto", href: "/contact" },
];

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    // Define header
    <header className="sticky top-0 z-50 border-b border-border bg-background/90 backdrop-blur-sm">
      <Container className="flex h-20 items-center justify-between">
        {/* Logo  */}
        <a href="/" className="flex items-center gap-2">
          <Dumbbell className="h-6 w-6 text-primary" />
          <span className="font-display text-xl font-bold text-text">FLG</span>
        </a>

        {/* Links desktop */}

        <nav className="hidden items-center gap-8 lg:flex">
          {/* I iterate through the array of navlinks and insert a link generated by a component -- the .map() array method, which transforms each element into something else */}
          {navLinks.map((link) => (
            <a
              key={link.label}
              href={link.href}
              className="font-body text-md text-text-muted transition-colors duration-200 hover:text-primary"
            >
              {link.label}
            </a>
          ))}
        </nav>

        {/* CTA desktop */}
        <div className="hidden lg:block">
          <Button href="/login" size="sm">
            Ingresar
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="2"
              stroke="currentColor"
              className="h-4 w-4 ml-1 "
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3"
              />
            </svg>
          </Button>
        </div>

        {/* Three-line button (mobile) */}
        <button
          onClick={() => setIsOpen((prev) => !prev)} // When you click on the three lines, the state changes from false to true and vice versa.
          className="text-text lg:hidden"
          aria-label={isOpen ? "Cerrar menu" : "Abrir menu"}
        >
          {/* If it's open, display X; otherwise, display the three-line button */}
          {isOpen ? (
            <X className="h-7 w-7 " />
          ) : (
            <Menu className="h-7 w-7" />
          )}{" "}
        </button>
      </Container>

      {/* Menu mobile */}
      {isOpen && ( // && is conditional rendering. If isOpen = true, it displays; if isOpen = false, it displays nothing.
        <div className="border-t border-border bg-background lg:hidden">
          <Container className="flex flex-col gap-4 py-6">
            {navLinks.map((link) => (
              <a
                key={link.label}
                href={link.href}
                onClick={() => setIsOpen(false)} // Set to false so that it closes when you click on a link
                className="font-body text-base text-text-muted transition-colors duration-200 hover:text-primary"
              >
                {link.label}
              </a>
            ))}
            <Button href="/login" size="sm" className="mt-2 w-full">
              Ingresar
            </Button>
          </Container>
        </div>
      )}
    </header>
  );
};

export default Navbar;
